name: shared
description: A shared package

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add any other dependencies the shared package uses

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
